<?php
/**
 * PushApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactional API
 *
 * # Introduction    This API is a service provided by [E-goi](www.e-goi.com) to send transactional messages.    Transactional Messaging is a 1-to-1 communication channel, usually from an organization directed to a specific consumer.   They can be triggered by:    * __Actions__ - The consumer interacts with the organization (ie.: online shopping);  * __Time__ - The consumer's actions are time-bounded by the organization (ie.: period of inactivity).    Because of the nature of these messages,   it is expected that the consumer is interested in the content of these messages.   Therefore, they have a different treatment from marketing messages, and have a higher acceptance and opening rate.    >DISCLAIMER  >  >Please notice that this platform is more delicate in regards to the nature and processing of its messages.  >  >It should NOT be used as a mean of mass marketing, scams, phishing or overall unruly behaviour.   >  >Failure to comply may lead to limitation of use and even termination of account.    ***
 *
 * OpenAPI spec version: V2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PushApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PushApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addApp
     *
     * Create App.
     *
     */
    public function testAddApp()
    {
    }

    /**
     * Test case for addPushTemplate
     *
     * Create Push Template.
     *
     */
    public function testAddPushTemplate()
    {
    }

    /**
     * Test case for deleteApp
     *
     * Remove App.
     *
     */
    public function testDeleteApp()
    {
    }

    /**
     * Test case for deletePushTemplate
     *
     * Remove Push Template.
     *
     */
    public function testDeletePushTemplate()
    {
    }

    /**
     * Test case for listApp
     *
     * Get an App.
     *
     */
    public function testListApp()
    {
    }

    /**
     * Test case for listApps
     *
     * Get All Apps.
     *
     */
    public function testListApps()
    {
    }

    /**
     * Test case for listPushTemplate
     *
     * Get an Push Template.
     *
     */
    public function testListPushTemplate()
    {
    }

    /**
     * Test case for listPushTemplates
     *
     * Get All Push Templates.
     *
     */
    public function testListPushTemplates()
    {
    }

    /**
     * Test case for sendPushMessages
     *
     * Send a Push Message.
     *
     */
    public function testSendPushMessages()
    {
    }

    /**
     * Test case for updateApp
     *
     * Update App.
     *
     */
    public function testUpdateApp()
    {
    }

    /**
     * Test case for updatePushTemplate
     *
     * Update Push Template.
     *
     */
    public function testUpdatePushTemplate()
    {
    }
}
